CREATE TABLE IF NOT EXISTS push_subscriptions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    account_id TEXT NOT NULL UNIQUE,
    endpoint TEXT NOT NULL,
    p256dh_key TEXT NOT NULL,
    auth_key TEXT NOT NULL,
    standard INTEGER NOT NULL DEFAULT 0,
    alert_follow INTEGER NOT NULL DEFAULT 0,
    alert_favourite INTEGER NOT NULL DEFAULT 0,
    alert_reblog INTEGER NOT NULL DEFAULT 0,
    alert_mention INTEGER NOT NULL DEFAULT 0,
    alert_poll INTEGER NOT NULL DEFAULT 0,
    alert_status INTEGER NOT NULL DEFAULT 0,
    alert_update INTEGER NOT NULL DEFAULT 0,
    alert_follow_request INTEGER NOT NULL DEFAULT 0,
    alert_quote INTEGER NOT NULL DEFAULT 0,
    alert_quoted_update INTEGER NOT NULL DEFAULT 0,
    alert_admin_sign_up INTEGER NOT NULL DEFAULT 0,
    alert_admin_report INTEGER NOT NULL DEFAULT 0,
    policy TEXT NOT NULL DEFAULT 'all',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
