import { scope } from "arktype";

/** Shared Mastodon API shapes compiled once for all parsers. */
export const mastodon = scope({
  VisibilityApi: "'public' | 'unlisted' | 'private' | 'direct'",
  AccountRefApi: {
    id: "string>0",
    username: "string>0",
    acct: "string>0",
    display_name: "string",
    avatar: "string",
  },
  AccountProfileApi: {
    id: "string>0",
    username: "string>0",
    acct: "string>0",
    display_name: "string",
    avatar: "string",
    header: "string",
    note: "string",
    followers_count: "number",
    following_count: "number",
    statuses_count: "number",
    locked: "boolean",
  },
  AccountCredentialsApi: {
    id: "string>0",
    display_name: "string",
    note: "string",
    avatar: "string",
    "header?": "string",
    username: "string>0",
    acct: "string>0",
    source: {
      "note?": "string",
      privacy: "string",
      sensitive: "boolean",
      language: "string | null",
      quote_policy: "string",
    },
  },
  AccountSummaryApi: {
    id: "string>0",
    username: "string>0",
    display_name: "string",
    acct: "string>0",
    avatar: "string",
    instance_name: "string>0",
  },
  MediaAttachmentApi: {
    id: "string",
    type: "string",
    url: "string",
    "preview_url?": "string",
    "description?": "string | null",
  },
  PreviewCardApi: {
    url: "string",
    title: "string",
    description: "string",
    type: "string",
    provider_name: "string",
    provider_url: "string",
    "image?": "string | null",
    "blurhash?": "string | null",
  },
  PollOptionApi: {
    title: "string",
    "votes_count?": "number | null",
  },
  PollApi: {
    id: "string>0",
    "expires_at?": "string | null",
    expired: "boolean",
    multiple: "boolean",
    votes_count: "number",
    "voters_count?": "number | null",
    "voted?": "boolean",
    "own_votes?": "number[]",
    options: "PollOptionApi[]",
  },
  RelationshipApi: {
    id: "string>0",
    following: "boolean",
    followed_by: "boolean",
    blocking: "boolean",
    muting: "boolean",
    requested: "boolean",
    requested_by: "boolean",
  },
  StatusPayloadApi: {
    id: "string>0",
    created_at: "string",
    content: "string",
    "spoiler_text?": "string",
    "sensitive?": "boolean",
    visibility: "VisibilityApi",
    "in_reply_to_id?": "string | null",
    "replies_count?": "number",
    "reblogs_count?": "number",
    "favourites_count?": "number",
    "favourited?": "boolean",
    "reblogged?": "boolean",
    "bookmarked?": "boolean",
    account: "AccountRefApi",
    "media_attachments?": "MediaAttachmentApi[]",
    "card?": "PreviewCardApi | null",
    "poll?": "PollApi | null",
    "reblog?": "StatusPayloadApi | null",
  },
});
