use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let dist = manifest_dir.join("../../admin-ui/dist");
    let embed_dir = out_dir.join("admin_ui_embed");
    let fallback = manifest_dir.join("admin_ui_fallback/index.html");

    println!("cargo:rerun-if-changed=admin_ui_fallback/index.html");
    if dist.exists() {
        println!("cargo:rerun-if-changed=../../admin-ui/dist");
    }

    fs::create_dir_all(&embed_dir).expect("create embed dir");

    let mut entries = Vec::new();
    if dist.exists() {
        collect_dist_files(&dist, &dist, &embed_dir, &mut entries);
    } else {
        let target = embed_dir.join("index.html");
        fs::copy(&fallback, &target).expect("copy fallback index.html");
        entries.push(EmbedEntry {
            web_path: "/admin/".to_owned(),
            file_name: "index.html".to_owned(),
            content_type: "text/html; charset=utf-8".to_owned(),
        });
    }

    write_generated_module(&out_dir, &entries);
}

struct EmbedEntry {
    web_path: String,
    file_name: String,
    content_type: String,
}

fn collect_dist_files(
    dist_root: &Path,
    current: &Path,
    embed_dir: &Path,
    entries: &mut Vec<EmbedEntry>,
) {
    for entry in fs::read_dir(current).expect("read dist directory") {
        let entry = entry.expect("read dist entry");
        let path = entry.path();
        if path.is_dir() {
            collect_dist_files(dist_root, &path, embed_dir, entries);
            continue;
        }

        let relative = path.strip_prefix(dist_root).expect("path inside dist root");
        let relative_str = relative.to_string_lossy().replace('\\', "/");
        let web_path = if relative_str == "index.html" {
            "/admin/".to_owned()
        } else {
            format!("/admin/{relative_str}")
        };
        let file_name = format!("file_{}", relative_str.replace(['/', '.', '-'], "_"));
        let target = embed_dir.join(&file_name);
        fs::copy(&path, &target).expect("copy embedded asset");
        entries.push(EmbedEntry {
            web_path,
            file_name,
            content_type: content_type_for_path(&relative_str),
        });
    }
}

fn content_type_for_path(path: &str) -> String {
    match Path::new(path)
        .extension()
        .and_then(|value| value.to_str())
        .unwrap_or_default()
    {
        "html" => "text/html; charset=utf-8",
        "js" => "application/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "webp" => "image/webp",
        "woff2" => "font/woff2",
        "woff" => "font/woff",
        "json" => "application/json; charset=utf-8",
        "ico" => "image/x-icon",
        _ => "application/octet-stream",
    }
    .to_owned()
}

fn write_generated_module(out_dir: &Path, entries: &[EmbedEntry]) {
    let mut source = String::from(
        "// @generated by build.rs — do not edit\n\
         pub(crate) fn lookup_embedded_asset(path: &str) -> Option<(&'static [u8], &'static str)> {\n\
             let normalized = normalize_admin_asset_path(path);\n\
             match normalized.as_str() {\n",
    );

    for entry in entries {
        source.push_str(&format!(
            "        \"{}\" => Some((include_bytes!(\"admin_ui_embed/{}\"), \"{}\")),\n",
            entry.web_path, entry.file_name, entry.content_type,
        ));
    }

    source.push_str(
        "        _ => None,\n\
             }\n\
         }\n\n\
         fn normalize_admin_asset_path(path: &str) -> String {\n\
             if path == \"/admin\" {\n\
                 return \"/admin/\".to_owned();\n\
             }\n\
             path.to_owned()\n\
         }\n",
    );

    fs::write(out_dir.join("admin_ui_assets.rs"), source).expect("write admin_ui_assets.rs");
}
