[package]
name = "cfwdon-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
async-stream = "0.3"
base64 = "0.22"
cfwdon-core.workspace = true
cfwdon-domain.workspace = true
futures-util = "0.3"
http = "1"
js-sys = "0.3"
serde.workspace = true
serde_json.workspace = true
time.workspace = true
url = "2"
urlencoding = "2"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-push-native = "0.4"
web-sys = { version = "0.3", features = [
    "Algorithm",
    "Crypto",
    "CryptoKey",
    "CryptoKeyPair",
    "RsaHashedImportParams",
    "SubtleCrypto",
    "WorkerGlobalScope",
] }
worker.workspace = true
worker-macros.workspace = true
